sudo: required
language: node_js
node_js:
  - "10"
services:
  - docker
# branches:
#   only:
#   - master
env:
  - DB_HOST=$DB_HOST DB_PORT=$DB_PORT DB_USER=$DB_USER DB_PASS=$DB_PASS DAILY_DB_NAME=$DAILY_DB_NAME RSS_DB_NAME=$RSS_DB_NAME HUGINN_DB_NAME=$HUGINN_DB_NAME KEY=$KEY MERCURY=$MERCURY HUGINN_RSS=$HUGINN_RSS  SENTRY=$SENTRY

install: 
  - chmod a+x deploy.sh && ./deploy.sh
notifications:
  email:
    recipients:
      - travis-ci@henry.wang
