sudo: required
language: node_js
node_js:
  - "9"
services:
  - docker
branches:
  only:
  - travis
env:
  - DB_HOST=$DB_HOST DB_POST=$DB_POST DB_NAME=$DB_NAME DB_USER=$DB_USER DB_PASS=$DB_PASS KEY=$KEY MERCURY=$MERCURY HUGINN_RSS=$yHUGINN_RSS DB_FEEDS_TABLE=$DB_FEEDS_TABLE

install: 
  - chmod a+x deploy.sh && ./deploy.sh

notifications:
  email:
    recipients:
      - henry@wangqiru.com
    on_success: never
