sudo: required

language: node_js

node_js:
  - "10"

services:
  - docker
  - postgresql


env:
  - DB_HOST=localhost DB_PORT=$DB_PORT DB_USER=postgres DB_PASS= DAILY_DB_NAME=daily_test RSS_DB_NAME=$RSS_DB_NAME HUGINN_DB_NAME=$HUGINN_DB_NAME KEY=$KEY MERCURY=$MERCURY HUGINN_RSS=$HUGINN_RSS  SENTRY=$SENTRY CHROME_ADDRESS=$CHROME_ADDRESS NATIONAL_RAIL_API=$NATIONAL_RAIL_API

before_script:
  - psql -c 'create database daily_test;' -U postgres

script: 'true'

before_install:
  - yarn install

install:
  - chmod a+x deploy.sh && ./deploy.sh

cache:
  yarn: true
  directories:
    - node_modules

notifications:
  email:
    recipients:
      - travis-ci@henry.wang
